### ISSUE TITLE
PSVersion 7 issues with Certificate mismatch

### ISSUE THREAD

**Issue by frznto** [dell/powershell-vxrail#1]
VxRail.API.Common.ps1 file still tries to handle certificates in the ways previous to PSVersion 7. Modifying the below lines, 115-117, to include the -SkipCertificateCheck allows the Invoke-RestMethod to connect and work. Tested in Visual Studio Code with PSVersion 7.3.4/Core on Windows 10.

            $response = Invoke-RestMethod -SkipCertificateCheck -Method $m -Uri $url -Headers $headers -ContentType $ContentType -TimeoutSec $TimeoutSec
        } else {
            $response = Invoke-RestMethod -SkipCertificateCheck -Method $m -Uri $url -Headers $headers -Body $Body -ContentType $ContentType -TimeoutSec $TimeoutSec

**Comment by CraigOLeary** [comment]
Hi @frznto, thanks for reaching out. Currently we only support PowerShell version <=5.x.
